# Generated by Django 3.0.5 on 2020-04-22 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200422_1514'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='profilePic',
            new_name='profile_pic',
        ),
    ]
