# Generated by Django 3.0.5 on 2020-04-17 07:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('meup', '0002_article_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(default=uuid.uuid4, editable=False, max_length=120, unique=True),
        ),
    ]
